### ISSUE TITLE
Error during code compilation

### ISSUE THREAD

**Issue by gorillagroup** [GoDataFeed/godatafeed-integration-m2#1]
We've noticed an error when running code compilation "php bin/magento setup:di:compile"

Error is
"[Exception]                                                                                                                                                                                               
  Warning: Cannot modify header information - headers already sent by (output started at /xxx/app/code/GoDataFeed/Integration/Api/OrderDataInterface.php:498)  
   in /xxx/app/code/GoDataFeed/Integration/Model/Product.php on line 4"

This error appears for both 2.0.x and 2.1.x versions.

Thank You

**Comment by mrthrowawaylabs** [comment]
* What version of php was used?
* Any modification made to the extension before being compiled?

**Comment by gorillagroup** [comment]
PHP version 5.6.31
no modifications

**Comment by mrthrowawaylabs** [comment]
The module has been built and tested around php 7+ and is listed as a prerequisite in the README.md of this module.

**Comment by gorillagroup** [comment]
I see now.

Thanks. Shouldn't it be optimized for PHP 5.6.x as long as 2.1.x Magento allows this version?
http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html

**Comment by gorillagroup** [comment]
Ok, now it is PHP 7.0.23 and still the same error.

**Comment by bangerkuwranger** [comment]
same issue w/ Magento Commerce v2.1.9 on PHP 7.0.23, Centos 7. Was able to get code to compile by commenting out line 4 of the product model (this will probably send invalid header with ordersync). Header modification should take place within the class methods, not before class declaration.

**Comment by mrthrowawaylabs** [comment]
@bangerkuwranger - Thank you for your suggestion! We are making some changes to the extension and will release an updated version soon.

@gorillagroup - Please remove line 4 in Model/Product.php that contains header info or wait for the new version that will be uploaded within the next 24hrs.

**Comment by gorillagroup** [comment]
Hello,

Can you update us with the status please? I can't find new release with the fix so far.

Thank You

**Comment by mrthrowawaylabs** [comment]
@gorillagroup - The latest release has been published on this repo. 

Please disable the existing module and delete the contents of the GoDataFeed app directory '/Integration' before installing the newest module. 

Below is the command to disable the existing module:
```php
php bin/magento module:disable GoDataFeed_Integration
```
