### ISSUE TITLE
not possible to install with composer require

### ISSUE THREAD

**Issue by janmyszkier** [GoDataFeed/godatafeed-integration-m2#2]
```
Could not find a matching version of package godatafeed/godatafeed-product-integration-module. Check the package spelling, your version constraint and that the package is available in a stability wh  
  ich matches your minimum-stability (stable)
```
most likely because the composer.json is not in the ROOT repository dir.

**Comment by gdfSheldon** [comment]
Thanks, we'll take a look.

**Comment by gdfSheldon** [comment]
Hi @janmyszkier we have uploaded our latest version (2.0.1). Thanks for reporting the bug, this should correct your issue. If you are able to test this on your end and still have some issues, feel free to reach out to our support@godatafeed.com or update with issue here.

Thanks,
Sheldon
