### ISSUE TITLE
Wrong return type for interface

### ISSUE THREAD

**Issue by AlexandrKozyr** [GoDataFeed/godatafeed-integration-m2#3]
When we installed the Godatafeed extension from the Magento marketplace it started generating this error whenever we tried to access the Magento API with anything: Message: Class "array" does not exist. Please note that namespace must be specified. {"exception":"[object] (Exception(code: 0);

**Comment by AlexandrKozyr** [comment]
added solution for this :
https://github.com/GoDataFeed/godatafeed-integration-m2/pull/4

**Comment by gdfSheldon** [comment]
Merged in Alex's fixes.
